2020/08_Flask/10_Large_project/puppycompanyblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user
from puppycompanyblog.models import User

class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password', validators =[DataReuired()])
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('UserName', validators = [DataRequired()])
    password = PasswordField('Password',validators=[DataRequired(), EqualTo('pass_confirm',message='Password must match!')])
    pass_confirm = PasswordField('Confirm Password',validators=[DataRequired()])

    def check_ 
    #Parei aula 110...7:09minutos

2020/08_Flask/10_Large_project/puppycompanyblog/__init__.py
# puppycompanyblog/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


app = Flask(__name__)

##########################################
########## DATABASE SETUP ################
##########################################
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///:'+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

##########################################
######### LOGIN CONFIGURATIONS ###########
##########################################
login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'


##########################################



from puppycompanyblog.core.views import core
app.register_blueprint(core)
from puppycompanyblog.error_pages.handlers import error_pages
app.register_blueprint(error_pages)

2020/08_Flask/10_Large_project/puppycompanyblog/core/views.py
# core/views.py

from flask import (
    render_template,
    request,
    Blueprint
)

core = Blueprint('core',__name__)

@core.route('/')
def index():
    # MORE TO COME!
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

2020/08_Flask/10_Large_project/puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

    <ul class = 'nav'>
        <li class = 'nav-link'>
            <a href = "{{url_for('core.index')}}">HOME</a>
        </li>

        <li class = 'nav-link'>
            <a href = "{{url_for('core.info')}}">About</a>
        </li>

        <li class = 'nav-link'>
            <a href = "{{url_for('core.index')}}">Log Out</a>
        </li>

        <li class = 'nav-link'>
            <a href = "{{url_for('core.index')}}">Account</a>
        </li>

        <li class = 'nav-link'>
            <a href = "{{url_for('core.index')}}">Create Post</a>
        </li>

        <li class = 'nav-link'>
            <a href = "{{url_for('core.index')}}">Log In</a>
        </li>

        <li class = 'nav-link'>
            <a href = "{{url_for('core.index')}}">Register</a>
        </li>
    </ul>



    {%block content%}

    {%endblock%}


    
</body>
</html>

2020/08_Flask/10_Large_project/puppycompanyblog/templates/index.html
{%extends "base.html"%}
{%block content%}

<div class = 'jumbotron'>
    <h1>Puppy Company Blog</h1>
</div>

{%endblock%}

2020/08_Flask/10_Large_project/puppycompanyblog/templates/info.html
{%extends "base.html"%}
{%block content%}
<div class = 'jumbotron'>
    <h1>Info about our company</h1>
    <p>Xxxxxx xxx xxxxxx xxxxxxx xxxxxx xxxxx xxx xxxxxx xxxxxxx xxxxxx xxxxx xxx xxxxxx xxxxxxx xxxxxxxxxxx xxx xxxxxx xxxxxxx xxxxxxxxxxx xxx xxxxxx xxxxxxx xxxxxx xxxxx xxx xxxxxx xxxxxxx xxxxxx</p>
</div>
{%endblock%}